source "https://rubygems.org"

gem 'jekyll', '3.5.2'
gem 'jekyll-coffeescript', '1.0.1'
gem 'jekyll-sass-converter', '1.3.0'
gem 'kramdown', '1.5.0'
gem 'maruku', '0.7.0'
gem 'rdiscount', '2.1.7'
gem 'redcarpet', '3.3.2'
gem 'RedCloth', '4.2.9'
gem 'liquid', '4.0.0'
gem 'pygments.rb', '0.6.3'
gem 'jemoji', '0.5.0'
gem 'jekyll-redirect-from', '0.12.1'
gem 'jekyll-sitemap', '0.8.1'
gem 'jekyll-feed', '0.3.1'

gem 'bourbon'
gem 'neat'
